### ISSUE TITLE
Tensorflow Tutorail with Docker

### ISSUE THREAD

**Issue by CarterTsai** [CarterTsai/blog#110]
### Pull Tensorflow

```
$> docker pull gcr.io/tensorflow/tensorflow
```
### docker-compose.yml

```
version: "2"
services:
    ap1:
        image: gcr.io/tensorflow/tensorflow
        # volumes:
        #     - ./openldap/:/backup
        ports:
            - "8888:8888"
        restart: always
        logging:
            driver: "json-file"
        network_mode: "bridge"
```
### Docker Compose Run

```
$> docker-compose up
```
