### ISSUE TITLE
Nginx create ssl and revert proxy with Docker

### ISSUE THREAD

**Issue by CarterTsai** [CarterTsai/blog#119]
https://hub.docker.com/r/tobi312/rpi-nginx/
```
$ mkdir -p /home/pi/{.ssl,html} && mkdir -p /home/pi/.config/nginx && touch /home/pi/.config/nginx/default.conf
``` 
and edit [default.conf](https://github.com/TobiasH87Docker/rpi-nginx/blob/master/default.conf)

```
$ openssl req -x509 -newkey rsa:4086 -subj "/C=/ST=/L=/O=/CN=localhost" -keyout "ssl.key" -out "ssl.crt" -days 3650 -nodes -sha256
```

### Docker-compose
```
version: "2.1"
services:
  proxy:
    image: tobi312/rpi-nginx
    volumes:
        - "/home/user/docker/nginx/.ssl:/etc/nginx/ssl:ro"
        - "/home/user/docker/nginx/.config:/etc/nginx/conf.d:ro"
        - "/home/user/docker/nginx/html:/var/www/html"
    ports:
        - "443:443"
    depends_on:
        - redmine
    restart: always
    networks:
        - back-tier
  redmine:
    image: joherma1/rpi-redmine
    ports:
        - "3001:3000"
    volumes:
        - "/home/user/docker/redmine/sqlite3:/usr/src/redmine/sqlite"
    restart: always
    networks:
      - back-tier

networks:
  back-tier:
```
### default.conf
```
server {
        listen         80;
        server_name    localhost;
        return         301 https://$server_name$request_uri;
}

server {
        gzip_types text/plain text/css application/json application/x-javascript text/xml application/xml application/xml+rss text/javascript;

        listen 443 default ssl;
        server_name localhost;
        ssl_certificate /etc/nginx/ssl/ssl.crt;
        ssl_certificate_key /etc/nginx/ssl/ssl.key;
        ssl_session_timeout 5m;
        ssl_protocols SSLv3 TLSv1;
        ssl_ciphers HIGH:!ADH:!MD5;
        ssl_prefer_server_ciphers on;

        error_page 497 https://$host:$server_port$request_uri;

        location /redmine {
                rewrite /redmine(.*) /$1  break;
                proxy_pass http://redmine:3000;
                proxy_redirect     off;
                proxy_set_header   Host $host;
                proxy_set_header X-Forwarded-Proto $scheme;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
}
```
P.S. redmine must equal docker-compose define redmine same name
